### ISSUE TITLE
Trigger callback upon component deletion, enable, installation

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#1111]
Trigger callback upon component deletion, enable, installation

**Comment by lianglee** [comment]
Need to check if after delete the callback is triggered.

**Comment by githubertus** [comment]
Just tried to make use of the `component:installed / component:enabled` callbacks to provide some defaults for my bio component - but they don't work.
General problem: At this stage (when the callback gets triggered in the class file) the component has not been executed yet. So the registered callback inside the component is still out of scope.

I gave it a first try by adding
`$dir  = ossn_route()->com;
include_once("{$dir}{$com}/ossn_com.php");`

right before the 'enabled' trigger, and that worked. 
But you better check whether it can be solved this way and has no bad side effects.

**Comment by lianglee** [comment]
So when it is being enabled/installed the callback is never triggered? (or callback triggered but component it self didn't executed as ossn_com.php is not yet called ?)

**Comment by githubertus** [comment]
Callback is triggered correctly,
but ossn_com.php is not yet called.
error log shows:
1. Trigger
2. com file
= wrong sequence 
If I understand your code correctly, all coms normally get loaded by loadComs() only, and that's too late. Even then,  a disabled component wouldn't load anyway. :)

**Comment by lianglee** [comment]
You are correct.  Actually when i added these callbacks the purpose was : 

1. Sometime we need to perform operations to database like (remove contents when component enabled/disabled)

But you right since the callback function will be of course in the installed/enabled/disabled component ossn_com.php and it never called which didn't make sense to have callback.

Which line you added $dir = ossn_route()->com; include_once("{$dir}{$com}/ossn_com.php");  (can you share your new components class file to skype i will take a look)

**Comment by lianglee** [comment]
Example:

1. ABC component,
2. ABC/ossn_com.php have callback to component installed/enable for itself (component:installed, ABC)
3. ossn_com.php isn't loaded ,  so the callback function from point 2 never be called form component ossn_com.php

**Comment by lianglee** [comment]
And i guess this only happens with following callbacks (as you mentioned)

       component:installed / component:enabled

**Comment by lianglee** [comment]
All these components enable/disable/installed/removed callbacks can be useful for 3rd party already enabled component which is monitoring these components stuff. 

To make these callback useful for current component on which action is being performed (enable/disable...) we need to surely include ossn_com.php before these two callbacks (component:installed / component:enabled) but :

Since we need to take care of ossn_com.xml file specially requirments mentioned inside it like ossn version,  other requirements (that need to meet before component get enabled),  without checking requirements may also result in error if requirement has been found on system.

Example: 
1. I have XYZ component and in its ossn_com.xml have requirement of ABC component (which is not present in system) or some php_function
2. Now if user try to enable component from components list it won't let to enable (enable button hidden) as it didn't met the requirements.
3. But if we call XYZ/ossn_com.php file directly it may result in to broken page (action page) error....

**Comment by githubertus** [comment]
You said:
"But you right since the callback function will be of course in the installed/enabled/disabled component ossn_com.php and it never called which didn't make sense to have callback.

Which line you added $dir = ossn_route()->com; include_once("{$dir}{$com}/ossn_com.php"); (can you share your new components class file to skype i will take a look)"

Actually, my bio component doesn't have an own class file.
I have added these lines experimentally in the OssnComponents class right before the component:enable ossn_trigger_callback() to load my component manually one time
------------------------------------------------------------------
You said:
"But if we call XYZ/ossn_com.php file directly it may result in to broken page (action page) error...."

Yeah, I see the problem. Okay, that would mean not to perform this direct include unconditionally, but run the checkRequirements() function in advance. And if that checks fails, the direct include will be not performed (since this component cannot be enabled later anyway)

**Comment by lianglee** [comment]
Yes agree ,

>
