### ISSUE TITLE
Friend Tagging Not Working

### ISSUE THREAD

**Issue by RGhostraven** [opensource-socialnetwork/opensource-socialnetwork#1145]
When I try and tag friends on my site, when I type in a friend's name, it just says "Searching" and never returns a result.

Site: www.secondbook.ga
OS: Ubuntu
Brower: Chrome

**Disable any additional component or theme you may have installed and verify whether this makes a difference:** No Change
**Revert any changes you may have made to the code and verify whether this makes a difference:** No Change

Test Account User/Pass: SBSupport / !!!Support321

To reproduce, simply log in and create a post, and hit the TAG button, Start typing Roger Ghostraven (the only friend for the support account) and see that nothing comes up.

Sysinfo is enabled at: http://www.secondbook.ga/ossninfo (Test account has admin info)

Error logging is enable per instructions, but the error log (OSSN_ERRORS) is empty.

Thanks for any help

**Comment by RGhostraven** [comment]
Here is the results of the ossninfo script. I didn't feel secure having the test account having admin access as people are signing up.

[ossninfo.pdf](https://github.com/opensource-socialnetwork/opensource-socialnetwork/files/1268343/ossninfo.pdf)

**Comment by RGhostraven** [comment]
I resolved this issue accidentally by simply CHMOD 775 on the installation directory. I don't know why the permissions had changed.

**Comment by githubertus** [comment]
Thanks for providing information ... which isn't making too much sense, though. As ossninfo shows:
You're NOT running the default theme
3rd party components are NOT turned off
Error logging is NOT turned on
... as recommeded in the How-to-report-a-bug doc.

Anyway, changing the permission from 755 to 775 can't be the solution. Instead you should

1. check that apache is running as www-data 
`ps aux | grep apache`
2. assure that all files and folders are owned by www-data
`chown -R www-data:www-data /var/www/html/ossn`
`chown -R www-data:www-data /var/www/ossn_data`
3. assure that all files are set to 644
`find /var/www/html/ossn -type f -exec chmod 644 {} \;`
`find /var/www/ossn_data -type f -exec chmod 644 {} \;`
4. assure that all directories are set to 755
`find /var/www/html/ossn -type d -exec chmod 755 {} \;`
`find /var/www/ossn_data -type d -exec chmod 755 {} \;`

Ossn MUST run that way without errors - otherwise there's something substantially wrong on your machine

**Comment by RGhostraven** [comment]
All the things that were recommended in how to report a bug were undone once my problem was fixed. I switched back to the theme I was using before, I turned on components 1 by 1 and tested, and I turned off error reporting and access to OSSNINFO. 

I did misspeak though, I did not 775 the directory, I used 755, but to be on the safe side I checked everything you listed. And everything is still working like a champ. Thank you so much for your help.
