### ISSUE TITLE
Installation requirement.

### ISSUE THREAD

**Issue by mj-fintech** [opensource-socialnetwork/opensource-socialnetwork#1155]
Ossn version - latest version
PHP version - 7/ I only could install the version 7.0 in linux server(ubuntu).
Error message - 
Error Log - 
Issue screenshots
![issue](https://user-images.githubusercontent.com/19509670/30778078-ff0f30ca-a099-11e7-9fb5-5939e2b8e1fb.png)

Cache enabled/disabled - Don't know.
Apache version (optional) - latest version. I just installed a day ago via sudo apt install. so it must be the latest version.
MySQL version (if possible) - same as above
Your website link (if possible) - http://189d989f.ngrok.io/
-----------------------------------------------------------------------------

I am trying to set up ossn server on my local machine(linux ubuntu server)/. 
What I did:
1. installed php via sudo apt install 
2. install mysql via sudo apt install
3. download the latest ossn, unzip, and put them in /var/www/html/ --> I wonder if the folder's name should be "public_html" or "html" is fine.
4. as you can seee from the screenshot, it is like that. What do I need to do to proceed further.

THanks,

**Comment by mj-fintech** [comment]
new link: http://26a78e42.ngrok.io

I uninstall php7.0 and installed the php5.6 version. It still gives me 500 Error. 
![issue2](https://user-images.githubusercontent.com/19509670/30778488-4190e67c-a0a5-11e7-8b81-078727894816.png)
Help me to resolve this. Thanks,

**Comment by githubertus** [comment]
Please understand that here we are discussing and trying to fix Ossn related issues only. Your screenshots show that your server isn't even configured to run PHP applications in general - no wonder that Ossn doesn't start.
There are numerous Readmes available on the web like https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu-16-04
and we suggest to follow those instructions in order to setup your server correctly, first.

**Comment by mj-fintech** [comment]
I have followed the exact same instruction you linked there. But I still got this page only and does not go anywhere. What should I do next? 
![issue3](https://user-images.githubusercontent.com/19509670/30784497-0a868e64-a124-11e7-9074-55c4a3fa4384.png)

**Comment by githubertus** [comment]
Since you're trying to become familiar with Ossn on a local machine anyway, I'd recommend to make use of our virtual image (see https://www.opensource-socialnetwork.org/download-vm-image) instead.

Additionally you may run phpinfo() on both your own server and the virtual machine in order to find out what's still missing to get Ossn started.

**Comment by lianglee** [comment]
Please follow the above instructions and make sure you installed php mcrypt extension...
