### ISSUE TITLE
Slow queries in Large amount of users and posts  (with SOLUTION)

### ISSUE THREAD

**Issue by jonathangoncalves** [opensource-socialnetwork/opensource-socialnetwork#1164]
Hi Guys, Recently I create 1000 fake users (with Aslam plugin, thanks!) with 100 posts each (i've had a lot of work with it), and I notice some slow queries. 
Every query with ossn_object and Order by was slow, so I tried an adjust:
According the link below, late ORDER BY row lookups are so slow, so, the better way to do this is pre-order before the rest of the query. Result: Jump from 5 sec to 0.4 sec (and i think it's still  slow).
My sugestion is change file classes/OssnObject.php line from 444  to 464 with this:

```
$params['params'] = array(
  "{$distinct} o.guid, o.time_created"
);
$params['wheres'] = array(
  $this->constructWheres($wheres)
);
$params['order_by'] = $options['order_by'];
$params['limit'] = $options['limit'];

if (!$options['order_by']) {
  $params['order_by'] = "o.guid ASC";
}

if (isset($options['group_by']) && !empty($options['group_by'])) {
  $params['group_by'] = $options['group_by'];
}
//override params
if (isset($options['params']) && !empty($options['params'])) {
  $params['params'] = $options['params'];
}
$params['from'] = '(SELECT * FROM ossn_object ORDER BY ' . str_replace('o.', '', $params['order_by']) . ') o';
$params['order_by'] = '';
$this->get = $this->select($params, true);
```

Sorry, I can't make a pull request...

I hope that it's help!

fonts: https://stackoverflow.com/a/14368637

**Comment by githubertus** [comment]
Thanks for having a look into optimization.
Can you please tell us which way you were retrieving these different execution times?
I mean, did you put timestamps in the beginning and end of searchObject() for example, or any other way?

**Comment by githubertus** [comment]
@jonathangoncalves 
I'm sorry to say, but your promising idea doesn't give reliable results.
You cannot limit the number of object records **in advance** without knowing what kind of type they will be.

Example:
To keep things simple let's assume our pagination is set to 1 and the latest action was inserting an advertisement in OssnAds. Thus the last record in ossn_objects will be of `type="site" subtype="ossnads"`

Moving to /home now using your code will trigger a

 `SELECT DISTINCT  o.guid, o.time_created FROM (SELECT * FROM ossn_object ORDER BY guid DESC LIMIT 0, 1) o`
which in fact will retrieve the just created last record now.

But since its subtype is "ossnads" instead of "wall", the following `WHERE(o.subtype='wall' AND o.type='user' AND (e0.type='object' AND e0.subtype='access' AND (1=1) AND e1.type='object' AND e1.subtype='poster_guid' AND (emd0.value=2) OR (emd0.value=3 AND emd1.value IN(2)))) `
returns FALSE, and as a result you'll see ... no posting on page 1 of your newsfeed.

**Comment by jonathangoncalves** [comment]
Sorry for not answer before.
Yes, I put a time() var before and after each query, and make a log with each query and time.
And you are right, I fix it and update the code below.

**Comment by githubertus** [comment]
Very much appreciated. Honestly I'm really curious about your solution :)

**Comment by jonathangoncalves** [comment]
Oh sorry... I need to improve my english LOL
I supposed to say above.
Apearentelly the GitHub can't style the code correctly with code tag, and I edited above..

Sooner I'll improve the FakeUser component to add fake posts too, and fix some bugs. I want to help this project more! 

So... Just see the first post , I changed it code.  
:)

**Comment by githubertus** [comment]
Hmm, actually I was trying this variant myself already, too.
You have removed the limit from the first select, and this way we're getting a correct result - that's true.
But the big disadvantage is: You're selecting the TOTAL number of objects now, and at least in my test community with 200.000 postings this even seems to slow down performance. With the original code I got around 4.7 secs, with this change it tends to 4.9 secs. So, only pre-ordering the objects DESCENDING is of no help.

Reg. fake postings: I'll upload an update which allows selecting the number of postings in a few minutes. This will make the usage a little more comfortable. :)
