### ISSUE TITLE
It seems the Open Source Social Network is already installed

### ISSUE THREAD

**Issue by simple4geek** [opensource-socialnetwork/opensource-socialnetwork#1420]
Everything was find during the installation process. I got to the admin page also. But while going to visite de site, i get this message here It seems the Open Source Social Network is already installed

What am i doing wrong ? i tryed PHP 5.6 and 7.0

thanks for answer

**Comment by githubertus** [comment]
Please provide some more details ... see https://www.opensource-socialnetwork.org/wiki/view/1101/how-to-report-a-bug-error

**Comment by homelancer** [comment]
If you are trying to install or reinstall OSSN to your previous setup, there is file named INSTALLED with a content of 1 under the public_html/installation folder.

The file indicates that the OSSN was previously install. Delete that INSTALLED file to continue with your installation.

**Comment by dogotaru** [comment]
I am getting the exact same message. Fresh install, admin user created and can login to dashboard, but view site shows: "it seems ossn is already installed". Do you have any idea what to check? Maybe rights issue for some folders.

**Comment by githubertus** [comment]
I can only repeat what I wrote on Dec 5.

**Comment by githubertus** [comment]
Thanks a lot.
I think the relevant hint is: You installed from a phone. From my experience andoid's chrome often tends to be 'superclever' - in this case remembering the first redirection to /installation as the default starting point of your site.
Actually, Ossn HAS saved the state of your finished installion correctly. Otherwise you wouldn't have got the "Already installed" message.
Aside from that you may remove or rename the complete installation directory right after the installation has finished. Most likely android will show a 'Page not found' message then. ;)
Hence the only idea i have is trying to clear the browser cache in a case like that.

**Comment by dogotaru** [comment]
True, I didn't clear the cache, but was using incognito mode. I have also experienced how overclever chrome is, and not only on mobile. Some of the cache can really annoy with its persistence, even in incognito.
I had no doubt, actually, that the installation has finished correctly, checked the db, files, nothing suggested otherwise.
From phone was impossible to debug anything, code editor of cpannel works like crap. I even switched-on my laptop ultimately in order to debug a bit, but didn't have to, anymore.
Renaming the folder: done that, sure :) .
Anyway, after validating from pc, normal chrome tab on android was obviously still redirecting to /installation but incognito wasn't, without touching the cache, so maybe there still is more to it than the browser cache.
And I bet simple4geek was also using a phone, or tablet maybe. I wonder what he ended up doing.
Thanks

**Comment by lianglee** [comment]
Maybe your hosting using internal cache,
