### ISSUE TITLE
Cross-device rename() use isn't possible

### ISSUE THREAD

**Issue by johndmulhausen** [opensource-socialnetwork/opensource-socialnetwork#1501]
Using storage solutions like DigitalOcean Block Storage volumes involve mounting from another device at a point like `/mnt/volume-sfo-2` 

However, things that need to move from that device into your droplet can't use rename() because of this bug:

https://bugs.php.net/bug.php?id=54097

This is fixed by changing OssnFile.php from:

```
rename($from . $fname, $to . $fname);
```

to

```
exec("mv ".escapeshellarg($from . $fname)." ".escapeshellarg($to . $fname));
```

**Comment by githubertus** [comment]
Good point indeed.
But we must have in mind that shell exec is forbidden with a lot of these cheap web hosters.
Thus it would need some extra checking during initial installation whether mv instead of rename is necessary AND available. Maybe the final command to be used could be stored in ossn.config.site then.

**Comment by lianglee** [comment]
and mv isn't available in post of non linux distros
