### ISSUE TITLE
Accounts Problem

### ISSUE THREAD

**Issue by RafailStratiotis** [opensource-socialnetwork/opensource-socialnetwork#1683]
A problem occurred

So when I'm logged on as a user 1 and the same time make i refresh,
and the same time the user 2 make login appears that he is connected as user1 and not user2. 

> **I tried it with my friend from different computers and IP.**

On the second case,
if user1 I don't refresh the same time of user2 make login.. the user2 has login in normally in account
but after.. if user1 and user2 make refresh in the same time going to log in either as user1 or user2...

Generally one of the two accounts will be confused and both computers will show that they are connected either as user1 or user2..
in this case when either of them does log out, both of them disconnect

**Comment by lianglee** [comment]
Just quoting our previous discussions 

**Arsalan Shah**

1. User1 is loggedin from his computer
2. User2 is loggedin from different computer
3. When user 2 is loggedin his profile says he is loggedin as User 1?
4. When any of the user logged out both logged out?

**Rafail**

**1. 1.Yes with different IP
2. 2.Yes with different IP
3. 3.(When user 2 is loggedin his profile says he is loggedin as User 1?)**

**A1.** Yes but this happens when user1 refresh his page at the same time that user 2 make login...
On the second case,

**A2.** if user1 I don't refresh the same time of user2 make login.. the user2 has login in normally in account
but... after.. if user1 and user2 make refresh in the same time going to log in either as user1 or user2...

Generally one of the two accounts will be confused and both computers will show that they are connected either as user1 or user2..

**4.(When any of the user logged out both logged out?)**
Yes but only in the case (3.) "A2."

**1.Can you tell if both users are logging in from different computer?**
yes .... and different IP...

**2.Can you further check if both users have different email saved in the database?**
yes they have different emails, different password etc.....

**Comment by lianglee** [comment]
https://www.opensource-socialnetwork.org/discussion/view/1932/security-issue-wrong-user-login-after-while-or-immediately

Seems same issue you are facing

**Comment by lianglee** [comment]
The issue is with your server i just sees many reported problems like this
and in the end it turned around to their servers configuration

Example

https://github.community/t5/Project-Development-Help-and/User-sessions-getting-mixed-up/td-p/18949

https://stackoverflow.com/questions/39099880/php-mixing-up-sessions

**Comment by RafailStratiotis** [comment]
yes it looks like you're right Arsalan
But how do I solve it?
should i go to VPS Server?

**Comment by lianglee** [comment]
I think its better to use a VPS eg linode.com

You can install a free VPS panel webuzo.com on it or any other panel you
prefer/without panel....

**Comment by RafailStratiotis** [comment]
At some time I would definitely go to VPS server
but now I'm just going to go earlier.  :P

Thank you very much Arsalan !
your dedication and help is very helpful to the community !

**Comment by lianglee** [comment]
You can use some cheaper vps options, most of good VPS starts from 5$ per month
