### ISSUE TITLE
Cancel of Friend Requests

### ISSUE THREAD

**Issue by TheGameHHH** [opensource-socialnetwork/opensource-socialnetwork#193]
If someone want to cancel a friend request, he gets an error message like 'Something went wrong please try again by reloading page'.

**Comment by lianglee** [comment]
Thanks for bug report we'll verify it as soon as possible.

@githubertus , @sathish4fri

**Comment by githubertus** [comment]
No such issue with my dev snapshot from Jan 4.
only a minor cosmetic one: request and cancallation message appear with red background instead of blue.

**Comment by lianglee** [comment]
i'll check this on 1.8

**Comment by sathish4fri** [comment]
yes @githubertus  said for me color is different . instead of friend request deleted , we can put some other words ..

**Comment by lianglee** [comment]
@sathish4fri  there is no need to put some other words.
I will verify this and close this ticket

**Comment by sathish4fri** [comment]
@lianglee   fine .

**Comment by githubertus** [comment]
Got it! Not your OWN friend requests were meant, but requests sent to you:
![friend-request](https://cloud.githubusercontent.com/assets/9904364/5793057/59f641b8-9f35-11e4-8b1b-514dcecc4572.png)
Fix #258 on the way :)
Besides that: Because it's a request sent by someone else, the button here should be 'Deny' instead of 'Cancel'
I'm going to fix it right now, since I just found 2 hardcoded strings. GRRRRR

**Comment by lianglee** [comment]
fixed!
