### ISSUE TITLE
[E] Enhance OssnFile and Include CDN option

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#2089]
with new methods

**Comment by lianglee** [comment]
Set a width height while uploading file so the image may be cropped as required

**Comment by TheCryptovist** [comment]
Hello can someone maybe assst me . I purchased the social premium site from ossbn 2 years ago . I alway was able to get updates and everything worked great until about 6 months ago. Now they did all the up dates and wanted to chare me after using my andriod app i paid to have custom work ddone on this project which was supposed to be mine.  Or for free since I piad then to build it they now use it and sell it for  299 it was built on my google acount anmd by my funding it to be built for me . Thats besides the point I will be added it to my github account for free <My problems is they after spending around 400 dollars deied to shut down my account becaiuse i wouldnt let them extort me for something that comes for free. Now they finally sent the iu[grade with none of the features in it at all they sent me the free versionb and i can do nothing with it. If someone would be  nice to send those features to me then I would be wqillinf ro senbd them the floating tool bars and andriods app that i paid for to anyuone that has need for it Whoever bought this bsuiness should be ashammed it used to count for something

**Comment by githubertus** [comment]
Oh, that's really a lot of changes!

Maybe a good chance to add WEBP images to allowed files...

**Comment by lianglee** [comment]
Yes why not :) I will add it
