### ISSUE TITLE
[B] btn-sm have no effect

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#2153]

**Comment by githubertus** [comment]
oops yes. time to replace bootstrap 5.0.0-beta3 by 5.1.3, I think. ;)
just tried that on GbG and the issue is fixed.
but it's introducing some other surprises like underlined links here and there and these little red spots :))
![red-notifs](https://user-images.githubusercontent.com/9904364/166442306-4ae503db-1ae2-4c1d-9600-b0deb8a0de26.png)

**Comment by lianglee** [comment]
bs5.0 in ossn was modified (custom code at end of file) maybe i will check
why

**Comment by lianglee** [comment]
![image](https://user-images.githubusercontent.com/805066/166672239-a8a30231-6459-47dd-ad15-7e5e3ed33bb7.png)   every upgrade of bs we need to add these from previous versions. 

But I still need to find why btn-sm have no effect

**Comment by githubertus** [comment]
' every upgrade of bs we need to add these'
No, for sure I won't do this - at least not with a theme of mine.
If this is really necesarry for keeping backward compatibility of some old compoments, I would add it to my theme's CSS - but leave bootstrap css untouched.

**Comment by lianglee** [comment]
Agree with you. To add in theme file instead of bootstrap.
