### ISSUE TITLE
warning: hostname opensource-socialnetwork.org does not resolve to address 46.101.248.179

### ISSUE THREAD

**Issue by dac2020** [opensource-socialnetwork/opensource-socialnetwork#2297]
Just FYI, our mail server didn't want to allow any emails from your network due to the above. 
This might be affecting others.

**Comment by dac2020** [comment]
Can someone from the dev group acknowledge this? It's a rather important problem to know about.

**Comment by lianglee** [comment]
Your mail server rejecting the emails? who is your mail provider?

**Comment by dac2020** [comment]
We run our own mail servers. It rejected it because the IP of your mail server didn't resolve to the correct one.

**Comment by lianglee** [comment]
Email reaches most of mailboxes fine including gmail, hotmail, yahoo, icloud etc.  So instead of hostname IP you should be validating SPF record to see if the sending domain have IP authorized or not.  

dig +short TXT opensource-socialnetwork.org

If you wanted us to validate your account please send us email with your email address name to admin@opensource-socialnetwork.org and notify us here we will manually validate your account as you are not getting emails. Alternatively you may use @gmail address

**Comment by dac2020** [comment]
The admin added the invalid IP to the servers hosts file which is how the email finally was received.

I'm just letting you know what happened. Emails from your site were not accepted due to the IP not resolving to the correct domain. 

What you decide to from with that information is up to you. I just took the time to report it :).

**Comment by lianglee** [comment]
@dac2020 thank you for reporting it and we appreciate it.  We are aware of it as some provider may reject email if hostname doesn't match the ip address. But due to many reasons our host not showing the IP we will look forward with our team to find a solution.
