### ISSUE TITLE
[B] Cover reposition issue due to layout updates in past

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#2305]
On demo https://demo.opensource-socialnetwork.org/u/administrator you may see you can move cover on left side making white spaces appear

![image](https://github.com/opensource-socialnetwork/opensource-socialnetwork/assets/805066/90f1df56-623f-49f5-880d-31a8aae5abd3)

Needs investigation

**Comment by githubertus** [comment]
Yes, because in the beginning the cover width of goblue was 1040
and Ossn.drag() is still using this fixed value, although the width of goblue changed to 1184 meanwhile.
We were aware that this would lead to issues (see comments in Ossn.drag) and did a first step by adding the theme config. But that's all. So what need's to be done is:
1. making the cover-upload action read the theme config and display a recommend width >= theme config width
2. replacing Ossn.drag() assumed fixed width of 1040 by the real theme cover width retrieved from the config

**Comment by lianglee** [comment]
Yes seems the boostrap changed the widths in previous updates when introducing XL layout. I think 2nd was is good i will try to look into it.

**Comment by lianglee** [comment]
```
<div id="ossn-theme-config" class="hidden" data-desktop-cover-height="200" data-minimum-cover-image-width="1200"></div>	
```
Uses ossn-theme-config (same as green by green theme) now themes should able to set the height and width. 

Still need to change the default cover width and height message !
