### ISSUE TITLE
paid for life time they ripped me off

### ISSUE THREAD

**Issue by wethecom** [opensource-socialnetwork/opensource-socialnetwork#2370]
paid for life time they ripped me off
wouldnt let me download
when i complained they erased mu account

**Comment by lianglee** [comment]
Dear Joseph Blanchard, 

Your account on community is blocked because you have used swear words and cursed without any reason.

You have paid for lifetime and you can continue to use.  Lifetime means you don't have to pay any monthly or yearly fee.  It works for lifetime.  However paid updates provided for 6 months and core updates provided for lifetime.

If you lost your cost or you want to download latest paid version you need to pay 49$ support fee which will renew your support for 6 months letting you download a latest copy again.

**Comment by lianglee** [comment]
*If you lost your copy or.....

**Comment by wethecom** [comment]
you chewed my ass out for asking a question,
your code is garbage nothing works
and who dosnt update thier code, and make people pay for updates
when you pay for a life time 
everything about your system is garbage and a rippoff and you are horrible people,
who chews someone out for recommending using drag and drop images for uploading , instead taking a good idea every social network uses you have to beret me and refuse to help me implement my own by answering one simple question where would be the best place to intercept the call

**Comment by lianglee** [comment]
Please don't open your ass in front of everyone.
Blocking you permanently now you lil bitch. 😂😂😂😂😂😂😂😂😂😂😂😂😂😂
Chew my 🍆🍆🍆🍆🍆🍆🍆🍆🍆🍆🍆
