### ISSUE TITLE
Mod Rewrite

### ISSUE THREAD

**Issue by tumenor** [opensource-socialnetwork/opensource-socialnetwork#240]
Mod rewrite is red on the installation page, even though mod rewrite is installed just fine.

**Comment by githubertus** [comment]
please, have a look at:
https://github.com/opensource-socialnetwork/opensource-socialnetwork/issues/182

which Ossn version were you trying to install?
and on what system?

**Comment by lianglee** [comment]
You can bypass validation by simply visiting: yoursite.com/nstallation/?page=settings it has been fixed in our feature release.

**Comment by githubertus** [comment]
@lianglee 
I just had a closer look at the new mod_rewrite check using curl:
This check is unreliable as before, because curl of course depends on correct hostname resolving, too.
If the hostname can't be resolved,
curl_error($curlinit); gives "Couldn't resolve host HOSTNAME" and
$result = curl_exec($curlinit);
will be FALSE.

I know, all this normally wouldn't happen with OSSN installed on a real hosting provider's site
but there's a good chance that people might run into this trap when trying OSSN at home on a machine which is not carefully configured.

Or to put it this way: If OSSN is making use of curl only here in this function, it's an unnecessary overhead because it doesn't make the mod-rewrite more reliable.

**Comment by lianglee** [comment]
Yes you are right

**Comment by sathish4fri** [comment]
yes
