### ISSUE TITLE
Cover photo resizing problems (upgraded)

### ISSUE THREAD

**Issue by gabrilll** [opensource-socialnetwork/opensource-socialnetwork#354]
Problems sending cover photo, the image comes out square and does not resize.
![redimensionar](https://cloud.githubusercontent.com/assets/547964/6283733/08443f90-b8c7-11e4-960f-b1dac576c6b9.jpg)

**Comment by PrashantRe** [comment]
+

**Comment by githubertus** [comment]
Since Ossn isn't supposed to be a special effects graphic software, I'm in line with this behavior. I'd even go a step further and add an error message like "Your picture is too small, the minimum size must be x * y pixel". Enlarging a picture which is too small to fit can only lead to bad results.

**Comment by gabrilll** [comment]
The same image is used on facebook its size is 600x452

**Comment by moneya** [comment]
@githubertus that is true... we need to resize image into various diamentions. like fb..
i will recommend converting images to webp.

**Comment by githubertus** [comment]
My idea is to give some reasonable guidelines instead:
1.) Don't use very much larger images (in this case 850x315), because it will cost us unnecessary bandwith
2.) Never use smaller images or completely different dimensions, because UP-scaling to the needed size will lead to distortion and a loss of quality in any case.

Besides that: To my opinion we're going to enter a dead-end-street on making every missing facebook feature an Ossn "issue". People who are 100% satisfied with facebook can go for it - this world doesn't need another 1:1 clone.

**Comment by lianglee** [comment]
@githubertus  :+1:

**Comment by gabrilll** [comment]
People want ease, I liked the idea of displaying warnings if the image is too small or too large, more related to resizing 1: 1 believe that people would hardly crop or resize by propia account.

**Comment by lianglee** [comment]
Please post idea on community site as it become difficult for us to track serious bugs.
