### ISSUE TITLE
OssnSmilies

### ISSUE THREAD

**Issue by PrashantRe** [opensource-socialnetwork/opensource-socialnetwork#361]
OssnSmilies component is not working.
It's showing no smiles in post and comment.

**Comment by githubertus** [comment]
@PrashantRe 
1. The current implementation of OssnSmilies is meant to work on posts only, not on comments.
2. You're right: it doesn't even work on posts. Because there are interferences with OssnEmbed.
I've left @lianglee a note already. (the input of Embed and Smilies has to be retrieved from $return instead of $params). With Smilies this is fixed already, while the fix in Embed is still missing.

**Comment by PrashantRe** [comment]
@bishopgodsey thanks again.its tested and working perfectly.
<a href="http://imgur.com/emZvOKL"><img src="http://i.imgur.com/emZvOKL.png" title="source: imgur.com" /></a>
