### ISSUE TITLE
Re-coding 2.3/3.x

### ISSUE THREAD

**Issue by Felli** [opensource-socialnetwork/opensource-socialnetwork#423]
I hope it's not a problem if I fix some of the things that I've found to be wrong or misspelled while I'm still working with this software. As most of the software at the moment has a lot of coding errors (And misspelled words.)

**Comment by lianglee** [comment]
It would be great if you fix, currently we are working on v3.0, so i suggest you to fix it on 3.x branch.

Thanks

**Comment by huckleberrypie** [comment]
Oh yeah, some of the grammar on the locale files leave a lot to be desired, I'm afraid. I know English isn't the developers' primary language, but since people from across the world especially in English-speaking countries will be using this software, improving the text prompts on the software itself and perhaps even on the website would leave a better impression among users.

**Comment by lianglee** [comment]
@huckleberrypie, yes there are grammar issues in language files. If you know the fix you can send us a pull request.
