### ISSUE TITLE
Firefox issue with default theme.

### ISSUE THREAD

**Issue by moneya** [opensource-socialnetwork/opensource-socialnetwork#438]
there is an issue with ossn 2.X default theme on firefox. Version 38.0.5
please view the image below.

![start-page-firefox](https://cloud.githubusercontent.com/assets/7353773/8056783/63592544-0ea3-11e5-947b-7222b1b87563.png)

**Comment by githubertus** [comment]
I've just been on http://alles-fuer-dein-kind.de/community/

with Win 8.1, same Firefox:
No Problem here.
Perhaps we should ask what OS he's using ... or whether he's running any special Firefox plugins...

**Comment by lianglee** [comment]
Its working fine

**Comment by ctlui** [comment]
Hi,

I've experiment the same issue, when this issue was open, I've make many tests on all house computers, some was ok and some others not,, even with same resolution.
Now all computers running windows 10.

So I find may be the cause, it's the lenght of the word 'login' in locale/ossn.xx.php ('site:login' => "Connexion",).
For French we have 'Connexion' and German is 'Anmelden'
If I just changed this translation in ossn.en.php to test the issue appear.

After some search I've changed:
display:inline-table;
to
display:inline-block;
in line:
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/themes/default/plugins/default/css/default.php#L127
https://github.com/opensource-socialnetwork/opensource-socialnetwork/blob/3.x/themes/default/plugins/default/css/default.php#L136

Now it's ok but don't know if it's correct. Need to find other users who have the issue to test.

Thanks - Eric

**Comment by githubertus** [comment]
Oh yeah: It looks like this is the old one (#265) which has never been really solved.
I don't know what the Firefox guys are changing from time to time. There have been releases (spring to summer 2015) when the problem disappeared, but since 40.x.x and above it's back again. Got it on my own site http://www.zytanien.de/forum/
And you're right Eric: it depends on the length of the login string. I remember, I did some tests on this issue myself some months ago.
I'm going to check if your fix makes a difference right now.

**Comment by lianglee** [comment]
I am reopening this

**Comment by githubertus** [comment]
Your fix is working, Eric!
before:
![hlc-inline-table](https://cloud.githubusercontent.com/assets/9904364/10262209/dd3140e8-69bd-11e5-8829-b5d841b13bb4.png)
after:
![hlc-inlineblock](https://cloud.githubusercontent.com/assets/9904364/10262210/ef3db096-69bd-11e5-8c62-1f95f6fef36c.png)
Just to note: That's still 2.3 (staring ashamed on the ground), but I think it'll work for 3.x, too

**Comment by lianglee** [comment]
@Zet can you send pull request? 

Thanks

**Comment by zet** [comment]
@lianglee request about what? O_o

**Comment by lianglee** [comment]
@Zet, i really sorry i was going to mention @githubertus  https://www.opensource-socialnetwork.org/u/zetman

**Comment by zet** [comment]
@lianglee no problem! :)
