### ISSUE TITLE
instalation error

### ISSUE THREAD

**Issue by nevenblue** [opensource-socialnetwork/opensource-socialnetwork#515]
please help me with this...

A system error has occurred. Please try again later. You may email the details of this error to the system administrator at husnul.hakim@negeriparapemimpi.com.
exception 'OssnDatabaseException' with message 'Field 'last_login' doesn't have a default value INSERT INTO ossn_users (`first_name`, `last_name`, `email`, `username`, `type`, `password`, `salt`, `activation`, `time_created`) VALUES ('husnul', 'hakim', 'husnul.hakim80@gmail.com', 'nevenblue', 'admin', '7fc9ec288b2055b3512238c1db98c2f1', '443d8c6a', '', '1441043523'); ' in D:\wamp\www\ossn\classes\OssnDatabase.php:77 Stack trace: #0 D:\wamp\www\ossn\classes\OssnDatabase.php(44): OssnDatabase->execute() #1 D:\wamp\www\ossn\classes\OssnUser.php(56): OssnDatabase->insert(Array) #2 D:\wamp\www\ossn\installation\actions\account.php(62): OssnUser->addUser() #3 D:\wamp\www\ossn\installation\libraries\ossn.install.php(175): include_once('D:\\wamp\\www\\oss...') #4 D:\wamp\www\ossn\installation\index.php(35): ossn_installation_actions() #5 {main}

**Comment by lianglee** [comment]
Ref: http://stackoverflow.com/questions/15438840/mysql-error-1364-field-doesnt-have-a-default-values

This is caused by the STRICT_TRANS_TABLES SQL mode defined in the %PROGRAMDATA%\MySQL\MySQL Server 5.6\my.ini file. Removing that setting and restarting MySQL should fix the problem.

If editing that file doesn't fix the issue, see http://dev.mysql.com/doc/refman/5.6/en/option-files.html for other possible locations of config files.
