### ISSUE TITLE
Take a look at pull #970

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#971]
Take a look at pull #970

1. Need to add input field
2. Action that handles port input.
3. Default value to default mysql port.

**Comment by lianglee** [comment]
@githubertus can you check if pull request 970 works?  the purpose of that pull request is when you add port in host name like localhost:3020 the system automatically should add port into config file.

**Comment by githubertus** [comment]
Yeah some time later. Want to finish the csv import component first. (The Readme evolved to be the most complicated part:) )

**Comment by rodrigodemacedo** [comment]
Before u test, I think I have to test if the default port is working and set 3306 in the config file when someone gives a localhost, for example, without the port.
I will test (and fix if necessary) in two or three days.

**Comment by githubertus** [comment]
No, it doesn't work with 'localhost' only

because there's a type mismatch, see:

mysqli::__construct ([ string $host = ini_get("mysqli.default_host") [, string $username = ini_get("mysqli.default_user") [, string $passwd = ini_get("mysqli.default_pw") [, string $dbname = "" [, int $port = ini_get("mysqli.default_port") [, string $socket = ini_get("mysqli.default_socket") ]]]]]] )

Thus, localhost without a port explicitely set means `port=null;` instead of `port='';`

**Comment by lianglee** [comment]
The default should be :
     
     ini_get("mysqli.default_port")

**Comment by lianglee** [comment]
fixed
