### ISSUE TITLE
unable to receive confirmation email

### ISSUE THREAD

**Issue by pradnya** [opensource-socialnetwork/opensource-socialnetwork#987]
while creating new ids, users are not receiving confirmation mails. Hence they are unable to proceed further.
Kindly resolve the same ASAP.
Our site name is Mykidjourney.16mb.com

**Comment by githubertus** [comment]
what email address are you using as 'Site Notification Email' ?

**Comment by pradnya** [comment]
My personal id of yahoo.
but, whenever a new client is logging in to create a new id under the domain they are unable to proceed it further since the confirmation E-mail from Open source account is not being sent to their Personal id's.
for e.g.
Step 1. Person A Loggin into mykidjourney.16mb.com
Step 2. They should receive a confirmation email so that they can make it active, but this confirmation Email is not being sent to them .Hence, unable to proceed further with the account activity.

Brgds

**Comment by pradnya** [comment]
Hi, friends requests also not being sent..
kindly let me know if you can resolve the issue at earliest.

Brgds

**Comment by lianglee** [comment]
in 16mb the smtp is not supported as i am sure, further you are using your yahoo id, you have to use noreply@yourwebsite.com

**Comment by githubertus** [comment]
@pradnya 
instead of repeatedly telling what's going wrong, please follow our advices and answer our questions.

Again: Set up an email client like Thunderbird or Outlook to connect to your provider and use the  address `noreply@Mykidjourney.16mb.com` to send a message to tomato@z-mans.net. Is this working?

Additionally please install the System Info component in order to provide exact infos about your community.

Last not least: We're used to solve each issue separately, as thing may become complicate enough with just one case. Thus, please open a seperate topic for other problems.
