### ISSUE TITLE
Embedded videos didn't show up in post

### ISSUE THREAD

**Issue by lianglee** [opensource-socialnetwork/opensource-socialnetwork#997]
Embeded videos didn't show up in post

**Comment by githubertus** [comment]
more precisely: the video size currently depends on the text line-width of the posting. If you have a full line of text above or below the video, the video can be seen, if there's no text at all (= linewidth:0), the video is hidden. 
This issue was introduced because of fix #962, the necessary css change is simply missing.

**Comment by aarnout** [comment]
he hello

i have this problem.
where i can find a solution for this?
thank you forhelping

Aarnout

**Comment by githubertus** [comment]
There:
https://github.com/opensource-socialnetwork/opensource-socialnetwork/commit/311a00fdaac5bc7c9320248bc187148c80711a51

Remove that line 415 from your css and you're done
